Consume mandatees from LMB
lblod/app-gelinkt-notuleren pull request #190
Opened 2024-08-15 08:34 UTC by lagartoverde

### Overview
This implements the LDES consumer which takes mandatees created on LMB and adds them to GN, In the corresponding public and private graphs

##### connected issues and PRs:
GN-4980

### Setup
You will need to replace the extra headers env variable, ask me for the auth token

### How to test/reproduce
Consume the data, check that now you have mandatees in http://mu.semte.ch/graphs/lmb-data-public, you should be able to find these mandatees in the frontend if you go to the corresponding administrative units

### Challenges/uncertainties
Waiting for a Niels answer related to in which graphs should be put de data

### Checks PR readiness
- [ ] UI: works on smaller screen sizes
- [ ] UI: feedback for any loading/error states
- [ ] Check cancel/go-back flows
- [ ] Check database state correct when deleting/updating (especially regarding relationships)
- [ ] changelog
- [ ] no new deprecations

2024-08-22 12:13 UTC, elpoelma requested changes
The mandatees and their related data seem to be ingested well.
Some notes:
- I had to use a different virtuoso.ini files (with different query and RAM limits), which I got from @lagartoverde 
- We should probably clear the cache after the postprocessing step

I have not yet been able to test what happens when adding a new mandatee to the LMB application.

2024-08-22 13:36 UTC, elpoelma commented
Tested, with the additional `DEFAULT_MU_AUTH_ALLOWED_GROUPS_HEADER`:
- It seems that adding a new mandatee to the lmb application seems to more-or-less go through (there still seem to be some issues on the side of lmb). As expected, I do have to restart the cache
- Unfortunately, it also seems the database contains a lot of duplicate triples: 
![image](https://github.com/user-attachments/assets/a7f5e8f0-6553-4c9b-a713-8cdf46e907d4)

2024-08-29 14:34 UTC, elpoelma commented on config/ldes-client/handleStreamEnd.ts
> +        }
This query fails on my end, it does not seem to be allowed to use the `OPTIONAL` keyword inside `INSERT` or `DELETE` bodies.

2024-08-29 14:36 UTC, elpoelma commented on config/ldes-client/handleStreamEnd.ts
> +        }
Additionally, I do not think we need to store the `identifier` object/relationship

2024-09-02 19:01 UTC, abeforgit approved these changes
this now works on my machine
It threw an error earlier today, but I tried again with a fresh qa backup and it ran without issue, so :shrug:

2024-09-03 14:17 UTC, elpoelma reviewed
This now works well on my end (with the beefy `virtuoso.ini` of course).
For this feature to work correctly a beefier virtuoso.ini is needed, as the service needs to be able to make queries/updates above 10000 triples.

I can correctly see the new mandatees appearing in the frontend.

I did notice there are still two ununused queries:
- `moveIdentifiersToPersonStagingQuery`
- `moveBirthdaysToPersonStagingQuery`

I would still omit the `identifier` property (even from the private graph), as we do not seem to require it.

2024-09-09 07:23 UTC, merged